### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s1-evaluacion-intermedia-aroatdlt#1]
Good job @aroatdlt  !!
Here you have some tips to improve the exercise

- [x] Organize CSS and image files in folders, be careful with naming. The *main* folder isn't intuitive. Remember you have a guide on [gitbook](https://books.adalab.es/materiales-front-end-e/sprint-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto)
- [x] Indent the code to improve readability and avoid bugs
- [x] Fix meta title
- [x] Add more semantic tags (nav, h1...)
- [x] Menu items should be anchors
- [x] Avoid uppercase on HTML, we can transform the text with CSS
- [x] Avoid tag selectors on CSS as `header`, `p`...

Once you have those fixed try to finish the styles. 
Your header looks really good, continue with the mobile version on the main area and go step by step:

- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), margin, padding...
- add cosmetic styles: color, background color, size, weight...

Then go for tablet and desktop versions.

Let me know if you have any doubts ;)

**Comment by nasivuela** [comment]
- Fix meta title

You have a `title` tag on `head`, it should be the title if the page, something like 'Adalab' could work in this case.

- Menu items should be anchors (also called links : )

I do not understand the last question, could you explain again?
Hope It helps, if something is still unclear, please tell me.

**Comment by nasivuela** [comment]
Ole!

I have unchecked one of the points, we are still missing an `h1` tag.

Also, what about adding a README ;)

**Comment by aroatdlt** [comment]
Hi Nasi!

Thank you again for your tips!! 

I did all the things but I have one question...why is it neccesary to add more styles to all the body if they are not common between them?? for example, font-size is different on header and on main...is it not better to add in each part his specific type of letter?

If you find something else that I can improve..tell me, please! =)

**Comment by nasivuela** [comment]
Well done!!

![](https://media.giphy.com/media/Mp4hQy51LjY6A/giphy.gif)

Usually, there are a font-family, a font-size, a font-weight and a color predominant in the pages, and we indicate them in the body. Also is a good practice to have a body background-color.

I know this page is small, but try to think bigger, let's imagine is the main page of a bigger site.
